import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { getFeaturedEvents } from '@/helper/api-util'
import EventList from '@/components/events/EventList'
import NewsletterRegistration from '@/components/input/newsletter-registration'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  const {events} = props

  if(events.length === 0) return <p>Loading .... </p>

  return (
    <>
      <Head>
        <title>NextJS Events App | Home Page | NextJS Events App Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <NewsletterRegistration />
        <h1 className="center">All Events</h1>
        <div>
          <EventList items={events} />
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const featuredEvents = await getFeaturedEvents();

  return {
    props: {
      events : featuredEvents
    },
    revalidate: 1800
  }
}
